// Auto-generated by LibreLane
module classifier_top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  input[3:0] x_int4,
  input[7:0] w_int8,
  input new_feat,
  input new_class,
  input[2:0] class_id,
  output[19:0] acc20,
  output[19:0] max_score,
  output[2:0] max_class
);
endmodule
